### ISSUE TITLE
 crash  on start

### ISSUE THREAD

**Issue by KnIfER** [dinuka9/crosswalk-shared-mode#1]
```
02-22 18:13:44.329 29714-29714/lk.dinuka.crosswalkshared E/AndroidRuntime: FATAL EXCEPTION: main
    Process: lk.dinuka.crosswalkshared, PID: 29714
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at c.b.a.d.c(:67)
        at c.b.a.f.r(:234)
        at c.b.a.f.e(:201)
        at c.b.a.n$b.b(:341)
        at c.b.a.n$b.onPostExecute(:317)
        at android.os.AsyncTask.finish(AsyncTask.java:651)
        at android.os.AsyncTask.access$500(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at org.xwalk.core.internal.XWalkCoreBridge.<init>(XWalkCoreBridge.java:32)
        at org.xwalk.core.internal.XWalkCoreBridge.init(XWalkCoreBridge.java:23)
        at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by KnIfER** [comment]
```
minifyEnabled false
```
